resources:
  repositories:
    - repository: devops
      type: github
      name: Rhinops-Sela/devops
      endpoint: Rhinops-Sela

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/metadata'
      artifact: 'metadata'
      publishLocation: 'pipeline'
  - task: Docker@2
    inputs:
      containerRegistry: 'NoamaDockerHub'
      repository: 'noamasela/fennec-base'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/DockerfileBase'
      tags: |
        $(Build.BuildId)
        $(Build.SourceVersion)
        latest
    displayName: 'Docker build and push'
