trigger: none

resources:
  pipelines:
  - pipeline: WebClient # identifier for the pipeline resource
    project:  fennec # project for the build pipeline; optional input for current project
    source: Rhinops-Sela.webclient
    trigger: 
      branches:
      - master
  - pipeline: Backend # identifier for the pipeline resource
    project:  fennec # project for the build pipeline; optional input for current project
    source: Rhinops-Sela.backend
    trigger: 
      branches:
      - master
  - pipeline: Components # identifier for the pipeline resource
    project:  fennec # project for the build pipeline; optional input for current project
    source: Rhinops-Sela.components
    trigger: 
      branches:
      - master
  - pipeline: Devops # identifier for the pipeline resource
    project:  fennec # project for the build pipeline; optional input for current project
    source: Rhinops-Sela.devops
    trigger: 
      branches:
      - master
steps:
- script: |
    pwd
    mkdir -p '$(Pipeline.Workspace)/build-workspace'
  displayName: 'create workspace'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'f6ab42a1-9699-4b5f-a01c-747fb9656456'
    definition: '4'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)/build-workspace/devops'
  displayName: 'Download devops metadata artifacts'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'f6ab42a1-9699-4b5f-a01c-747fb9656456'
    definition: '5'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)/build-workspace/backend'
  displayName: 'Download backend artifacts'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'f6ab42a1-9699-4b5f-a01c-747fb9656456'
    definition: '7'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)/build-workspace/components'
  displayName: 'Download components artifacts'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'f6ab42a1-9699-4b5f-a01c-747fb9656456'
    definition: '1'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)/build-workspace/webclient'
  displayName: 'Download webclient artifacts'

- script: |
    cp $(Pipeline.Workspace)/build-workspace/devops/metadata/Dockerfile $(Pipeline.Workspace)/build-workspace/Dockerfile
  displayName: 'Copy Dockerfile to build workspace'

- script: |
    cp $(Pipeline.Workspace)/build-workspace/devops/metadata/nginx.conf $(Pipeline.Workspace)/build-workspace/nginx.conf
  displayName: 'Copy nginx.conf to build workspace'

- task: Docker@2
  inputs:
    containerRegistry: 'NoamaDockerHub'
    repository: 'noamasela/fennec'
    command: 'buildAndPush'
    Dockerfile: '$(Pipeline.Workspace)/build-workspace/Dockerfile'
    tags: |
      $(Build.BuildId)
      $(Build.SourceVersion)
      latest
  displayName: 'Docker build and push'
