resources:
  repositories:
    - repository: devops
      type: github
      name: Rhinops-Sela/devops
      endpoint: Rhinops-Sela

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm install pm2
      npm run build
    displayName: 'npm install and run'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/dist'
      artifact: 'dist'
      publishLocation: 'pipeline'
    displayName: 'Publish dist'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/node_modules'
      artifact: 'node_modules'
      publishLocation: 'pipeline'
    displayName: 'Publish node_modules'

# - job: Publish
#   displayName: Publish a new container image
#   condition: and(succeeded(), eq(variables['publish'], 'true'))
#   dependsOn: Build
#   steps:
#     - template: build-and-push.yaml@devops 