apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: zipkin
  labels:
    run: zipkin
spec:
  ports:
  - port: 80
    targetPort: 9411
    protocol: TCP
    name: http
  selector:
    run: zipkin