name: build-and-push-Base

on:
  push:
    branches:
      - develop
    paths:
      - devops/DockerfileBase
jobs:      
  build-and-Push-Base-Image:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2 
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: blancahot
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: blancahot/fennec-base:${{ github.run_number }},blancahot/fennec-base:latest,blancahot/fennec-base:develop
          file: devops/DockerfileBase
    