name: fennec-download-artifacts-build-push

on:
  workflow_run:
    workflows: ["fennec-CI"]
    types:
      - completed

jobs:  
  download-artifacts-build-and-push-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: create workspace
        run: |
          pwd
          mkdir -p "$GITHUB_WORKSPACE/build-workspace"

      - name: download artifacts-components
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: fennec-CI.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: components
          path: ${{ github.workspace }}/build-workspace/components/components
          check_artifacts: true

      - name: download artifacts-backend
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: fennec-CI.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: node_modules
          path: ${{ github.workspace }}/build-workspace/backend/node_modules
          check_artifacts: true
 
      - name: download artifacts-backend
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: fennec-CI.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: dist
          path: ${{ github.workspace }}/build-workspace/backend/dist
          check_artifacts: true
     
      - name: download artifacts-webclient
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: fennec-CI.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: wizard
          path: ${{ github.workspace }}/build-workspace/webclient/wizard
          check_artifacts: true

      - name: download artifacts-fennec
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: fennec-CI.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: fennec
          path: ${{ github.workspace }}/build-workspace/fennec/fennec
          check_artifacts: true
          
      - name: Copy nginx.conf to build workspace
        run: |
          cp devops/metadata/nginx.conf ${{ github.workspace }}/build-workspace/nginx.conf
      
      - name: Copy Dockerfile to build workspace
        run: |
          cp devops/metadata/Dockerfile ${{ github.workspace }}/build-workspace/Dockerfile
          cd ${{ github.workspace }}/build-workspace
          ls
          
      - name: Copy script.sh to build workspace
        run: |
          cp devops/metadata/script.sh ${{ github.workspace }}/build-workspace/script.sh
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: blancahot
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        if: contains('refs/heads/develop', github.ref)
        id: docker_build_develop
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: blancahot/fennec:${{ github.run_number }},blancahot/fennec:latest,blancahot/fennec:develop
          context: ${{ github.workspace }}/build-workspace/
          
      - name: Build and push
        if: "!contains('refs/heads/develop', github.ref)"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: blancahot/fennec:${{ github.run_number }},blancahot/fennec:latest
          context: ${{ github.workspace }}/build-workspace/
